[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[project]
name = "DataML"
version = "2026.9.1.2"
dependencies = [
    "numpy",
    "h5py",
    "tensorflow",
    "pydot",
    "graphviz",
    "scipy",
    "pandas",
    "matplotlib",
    "tf-keras",
    "scikeras",
    "scikit-learn>=1.8,<1.9",
]

authors = [{ name="Nicola Ferralis", email="ferralis@mit.edu" },]
description = "Multilabel machine learning for combined experimental data"
readme = "README.md"
requires-python = ">=3.9"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
classifiers = [
    "Operating System :: OS Independent",
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Physics",
]

[project.scripts]
DataML = "DataML:DataML"
DataML_DF = "DataML_DF:DataML_DF"
CorrAnalysis = "CorrAnalysis:CorrAnalysis"
DataML_Maker = "DataML_Maker:DataML_Maker"
DataML_BatchMaker = "DataML_BatchMaker:DataML_BatchMaker"
DataML_DAE = "DataML_DAE:DataML_DAE"
DataML_VAE = "DataML_VAE:DataML_VAE"
DataML_KDE = "DataML_KDE:DataML_KDE"
ConvertNormLabels = "ConvertNormLabels:ConvertNormLabels"
ConvertParamLabels = "ConvertParamLabels:ConvertParamLabels"
GetClasses = "GetClasses:GetClasses"

[project.urls]
Homepage = "https://github.com/feranick/DataML"
Issues = "https://github.com/feranick/DataML/issues"

[tool.hatch.build.targets.wheel]
sources = ["src"]
include = ["src/*.py"]

[tool.hatch.build.targets.sdist]
only-include = ["src", "README.md", "LICENSE"]